language: node_js
node_js:
    - "8"
    - "10"

cache:
    directories:
        - "node_modules"

before_script:
    - npm install
    - npm run lint
scripts:
    - npm run cover
after_success:
    - codecov
